# config.py

from binance.client import Client

# -----------------------------------------------
# 타임프레임 세트 정의
# -----------------------------------------------
# (1) [15m, 1h, 4h]
timeframe_set_1 = [
    (Client.KLINE_INTERVAL_4HOUR, 6),      # 4h 60
    (Client.KLINE_INTERVAL_1HOUR, 24),      # 1h 80
    (Client.KLINE_INTERVAL_15MINUTE, 96),  # 15m 100
]

# (2) [5m, 15m, 1h]
timeframe_set_2 = [
    # (Client.KLINE_INTERVAL_1HOUR, 6),      # 1h 80
    # (Client.KLINE_INTERVAL_15MINUTE, 24),  # 15m 100
    (Client.KLINE_INTERVAL_5MINUTE, 36),   # 5m 120
]

###############################################################################
#                         (1) 15m, 1h, 4h 세트
#
#     주로 15분 봉(15m)을 매매 기준으로 하고,
#     1시간 봉(1h)과 4시간 봉(4h) 지표를 참고 (멀티타임프레임 분석)
###############################################################################
params_set_1 = {
    # ----------------------
    # 4시간 봉(4h) 파라미터
    # ----------------------
    "4h": {
        "adx_length": 28,
        "chop_length": 28,
        "macd_fast": 12,
        "macd_slow": 26,
        "macd_signal": 9,
        "ichimoku_tenkan": 9,   # 보통 기본값 유지
        "ichimoku_kijun": 26,   # 보통 기본값 유지
        "ichimoku_senkou": 52,  # 보통 기본값 유지
        "bb_length": 20,
        "bb_std": 2.0,
        "kc_length": 20,
        "kc_scalar": 1.5,
        "supertrend_length": 14,
        "supertrend_multiplier": 3.0,
        "psar_step": 0.02,
        "psar_max_step": 0.2,
        "cksp_len1": 10,
        "cksp_len2": 20,
        "aroon_length": 14,
        "stc_fast": 14,
        "stc_slow": 28,
        "stc_factor": 0.5,
        "rsi_length": 14,
        "stoch_k": 14,
        "stoch_d": 3,
        "stoch_smooth": 3,
        "cci_length": 20,
        "cci_constant": 0.015,
        "pvo_fast": 12,
        "pvo_slow": 26,
        "pvo_signal": 9,
        "mfi_length": 14,
        # 추가(추세/횡보 판단용)
        "ttm_length": 15,
        "kst_roc1": 9,
        "kst_roc2": 13,
        "kst_roc3": 15,
        "kst_roc4": 20,
        "kst_smroc1": 6,
        "kst_smroc2": 6,
        "kst_smroc3": 6,
        "kst_smroc4": 6,
        "kst_signal": 9,
        "vhf_length": 14,
        "er_length": 10,
        "inertia_r": 14,
        "vortex_length": 14,
        "amat_fast": 10,
        "amat_slow": 20,
        "tsignals_length": 14,
        "kama_length": 10,
        "kama_fast": 2,
        "kama_slow": 30,
        "donchian_lower": 20,
        "donchian_upper": 20,
        "slope_length": 10,
        "atr_length": 14,
    },

    # ----------------------
    # 1시간 봉(1h) 파라미터
    # ----------------------
    "1h": {
        "adx_length": 20,
        "chop_length": 20,
        "macd_fast": 12,
        "macd_slow": 26,
        "macd_signal": 9,
        "ichimoku_tenkan": 9,
        "ichimoku_kijun": 26,
        "ichimoku_senkou": 52,
        "bb_length": 20,
        "bb_std": 2.0,
        "kc_length": 20,
        "kc_scalar": 1.5,
        "supertrend_length": 12,
        "supertrend_multiplier": 2.5,
        "psar_step": 0.02,
        "psar_max_step": 0.2,
        "cksp_len1": 10,
        "cksp_len2": 20,
        "aroon_length": 14,
        "stc_fast": 14,
        "stc_slow": 28,
        "stc_factor": 0.5,
        "rsi_length": 14,
        "stoch_k": 14,
        "stoch_d": 3,
        "stoch_smooth": 3,
        "cci_length": 20,
        "cci_constant": 0.015,
        "pvo_fast": 12,
        "pvo_slow": 26,
        "pvo_signal": 9,
        "mfi_length": 14,
        # 추가
        "ttm_length": 15,
        "kst_roc1": 9,
        "kst_roc2": 13,
        "kst_roc3": 15,
        "kst_roc4": 20,
        "kst_smroc1": 6,
        "kst_smroc2": 6,
        "kst_smroc3": 6,
        "kst_smroc4": 6,
        "kst_signal": 9,
        "vhf_length": 14,
        "er_length": 10,
        "inertia_r": 14,
        "vortex_length": 14,
        "amat_fast": 10,
        "amat_slow": 20,
        "tsignals_length": 14,
        "kama_length": 10,
        "kama_fast": 2,
        "kama_slow": 30,
        "donchian_lower": 20,
        "donchian_upper": 20,
        "slope_length": 10,
        "atr_length": 14,
    },

    # ----------------------
    # 15분 봉(15m) 파라미터
    # ----------------------
    "15m": {
        "adx_length": 14,
        "chop_length": 14,
        "macd_fast": 12,
        "macd_slow": 26,
        "macd_signal": 9,
        "ichimoku_tenkan": 9,
        "ichimoku_kijun": 26,
        "ichimoku_senkou": 52,
        "bb_length": 20,
        "bb_std": 2.0,
        "kc_length": 20,
        "kc_scalar": 1.5,
        "supertrend_length": 10,
        "supertrend_multiplier": 2.0,
        "psar_step": 0.02,
        "psar_max_step": 0.2,
        "cksp_len1": 9,
        "cksp_len2": 18,
        "aroon_length": 14,
        "stc_fast": 14,
        "stc_slow": 28,
        "stc_factor": 0.5,
        "rsi_length": 14,
        "stoch_k": 14,
        "stoch_d": 3,
        "stoch_smooth": 3,
        "cci_length": 20,
        "cci_constant": 0.015,
        "pvo_fast": 12,
        "pvo_slow": 26,
        "pvo_signal": 9,
        "mfi_length": 14,
        # 추가
        "ttm_length": 15,
        "kst_roc1": 9,
        "kst_roc2": 13,
        "kst_roc3": 15,
        "kst_roc4": 20,
        "kst_smroc1": 6,
        "kst_smroc2": 6,
        "kst_smroc3": 6,
        "kst_smroc4": 6,
        "kst_signal": 9,
        "vhf_length": 14,
        "er_length": 10,
        "inertia_r": 14,
        "vortex_length": 14,
        "amat_fast": 10,
        "amat_slow": 20,
        "tsignals_length": 14,
        "kama_length": 10,
        "kama_fast": 2,
        "kama_slow": 30,
        "donchian_lower": 20,
        "donchian_upper": 20,
        "slope_length": 10,
        "atr_length": 14,
    },
}


###############################################################################
#                         (2) 5m, 15m, 1h 세트
#
#     주로 5분 봉(5m)을 매매 기준으로 하고,
#     15분 봉(15m)과 1시간 봉(1h) 지표를 참고 (멀티타임프레임 분석)
###############################################################################
params_set_2 = {
    # ----------------------
    # 1시간 봉(1h) 파라미터
    # ----------------------
    "1h": {
        "adx_length": 20,
        "chop_length": 20,
        "macd_fast": 12,
        "macd_slow": 26,
        "macd_signal": 9,
        "ichimoku_tenkan": 9,
        "ichimoku_kijun": 26,
        "ichimoku_senkou": 52,
        "bb_length": 20,
        "bb_std": 2.0,
        "kc_length": 20,
        "kc_scalar": 1.5,
        "supertrend_length": 12,
        "supertrend_multiplier": 2.5,
        "psar_step": 0.02,
        "psar_max_step": 0.2,
        "cksp_len1": 10,
        "cksp_len2": 20,
        "aroon_length": 14,
        "stc_fast": 14,
        "stc_slow": 28,
        "stc_factor": 0.5,
        "rsi_length": 14,
        "stoch_k": 14,
        "stoch_d": 3,
        "stoch_smooth": 3,
        "cci_length": 20,
        "cci_constant": 0.015,
        "pvo_fast": 12,
        "pvo_slow": 26,
        "pvo_signal": 9,
        "mfi_length": 14,
        # 추가
        "ttm_length": 15,
        "kst_roc1": 9,
        "kst_roc2": 13,
        "kst_roc3": 15,
        "kst_roc4": 20,
        "kst_smroc1": 6,
        "kst_smroc2": 6,
        "kst_smroc3": 6,
        "kst_smroc4": 6,
        "kst_signal": 9,
        "vhf_length": 14,
        "er_length": 10,
        "inertia_r": 14,
        "vortex_length": 14,
        "amat_fast": 10,
        "amat_slow": 20,
        "tsignals_length": 14,
        "kama_length": 10,
        "kama_fast": 2,
        "kama_slow": 30,
        "donchian_lower": 20,
        "donchian_upper": 20,
        "slope_length": 10,
        "atr_length": 14,
    },

    # ----------------------
    # 15분 봉(15m) 파라미터
    # ----------------------
    "15m": {
        "adx_length": 14,
        "chop_length": 14,
        "macd_fast": 12,
        "macd_slow": 26,
        "macd_signal": 9,
        "ichimoku_tenkan": 9,
        "ichimoku_kijun": 26,
        "ichimoku_senkou": 52,
        "bb_length": 20,
        "bb_std": 2.0,
        "kc_length": 20,
        "kc_scalar": 1.5,
        "supertrend_length": 10,
        "supertrend_multiplier": 2.0,
        "psar_step": 0.02,
        "psar_max_step": 0.2,
        "cksp_len1": 9,
        "cksp_len2": 18,
        "aroon_length": 14,
        "stc_fast": 14,
        "stc_slow": 28,
        "stc_factor": 0.5,
        "rsi_length": 14,
        "stoch_k": 14,
        "stoch_d": 3,
        "stoch_smooth": 3,
        "cci_length": 20,
        "cci_constant": 0.015,
        "pvo_fast": 12,
        "pvo_slow": 26,
        "pvo_signal": 9,
        "mfi_length": 14,
        # 추가
        "ttm_length": 15,
        "kst_roc1": 9,
        "kst_roc2": 13,
        "kst_roc3": 15,
        "kst_roc4": 20,
        "kst_smroc1": 6,
        "kst_smroc2": 6,
        "kst_smroc3": 6,
        "kst_smroc4": 6,
        "kst_signal": 9,
        "vhf_length": 14,
        "er_length": 10,
        "inertia_r": 14,
        "vortex_length": 14,
        "amat_fast": 10,
        "amat_slow": 20,
        "tsignals_length": 14,
        "kama_length": 10,
        "kama_fast": 2,
        "kama_slow": 30,
        "donchian_lower": 20,
        "donchian_upper": 20,
        "slope_length": 10,
        "atr_length": 14,
    },

    # ----------------------
    # 5분 봉(5m) 파라미터
    # ----------------------
    "5m": {
        "adx_length": 10,
        "chop_length": 10,
        # 5분봉 MACD는 좀 더 빠른 편의 파라미터 사용 예시
        "macd_fast": 8,
        "macd_slow": 21,
        "macd_signal": 7,
        "ichimoku_tenkan": 6,
        "ichimoku_kijun": 16,
        "ichimoku_senkou": 32,
        "bb_length": 20,
        "bb_std": 2.0,
        "kc_length": 20,
        "kc_scalar": 1.5,
        "supertrend_length": 7,
        "supertrend_multiplier": 1.8,
        "psar_step": 0.02,
        "psar_max_step": 0.2,
        "cksp_len1": 9,
        "cksp_len2": 18,
        "aroon_length": 14,
        # 5분봉 진입 타이밍을 빠르게 잡기 위해 STC도 빠르게
        "stc_fast": 9,
        "stc_slow": 21,
        "stc_factor": 0.5,
        "rsi_length": 14,
        "stoch_k": 14,
        "stoch_d": 3,
        "stoch_smooth": 3,
        "cci_length": 20,
        "cci_constant": 0.015,
        "pvo_fast": 12,
        "pvo_slow": 26,
        "pvo_signal": 9,
        "mfi_length": 14,
        # 추가
        "ttm_length": 15,
        "kst_roc1": 9,
        "kst_roc2": 13,
        "kst_roc3": 15,
        "kst_roc4": 20,
        "kst_smroc1": 6,
        "kst_smroc2": 6,
        "kst_smroc3": 6,
        "kst_smroc4": 6,
        "kst_signal": 9,
        "vhf_length": 14,
        "er_length": 10,
        "inertia_r": 14,
        "vortex_length": 14,
        "amat_fast": 10,
        "amat_slow": 20,
        "tsignals_length": 14,
        "kama_length": 10,
        "kama_fast": 2,
        "kama_slow": 30,
        "donchian_lower": 20,
        "donchian_upper": 20,
        "slope_length": 10,
        "atr_length": 14,
    },
}
